feat password reset
Job79/lectoraat-smart-energy pull request #81
Opened 2024-01-13 19:58 UTC by studentThomas

Ik heb nu dat als manager persoon maakt de mail app opent en wachtwoord en mail doorstuurt in die mail. Als user inlogd kan hij allen bij /calculators voor andere dingen moet hij eerst account "activeren" door standaar wachtwoord te veranderen naar eigen. Ik kan niet automatish wachtwoord laten invullen wacht wachtwoord van user kan je niet uit pocketbase halen

2024-01-14 16:02 UTC, Job79 requested changes

2024-01-14 16:02 UTC, Job79 commented on frontend/libs/features/users/src/pages/edit/user-edit.component.ts
> +      const chars = '0123456789abcdefghijklmnopqrstuvwxyz!@#$%^&*';
Mischien beetje een nitpick, maar voor wachtwoorden wil je eigenlijk een secure random functie gebruiken. Anders zou je mogelijk het wachtwoord van nieuwe gebruikers kunnen voorspellen zou je een gehele lijst achter elkaar aanmaken.

Heb een functie gevonden die `crypto.getRandomValues` gebruikt, deze is secure random:
```
var generatePassword = (
  length = 20,
  characters = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz~!@-#$'
) =>
  Array.from(crypto.getRandomValues(new Uint32Array(length)))
    .map((x) => characters[x % characters.length])
    .join('')
```

2024-01-14 18:47 UTC, studentThomas commented on frontend/libs/core/src/models/user.interface.ts
> +  isActivated: boolean;
Kan jij dat doen? Toen ik dat probeerde op school had ik toen iets dat apple dat blokte

2024-01-14 18:51 UTC, studentThomas commented on frontend/libs/core/src/models/user.interface.ts
> +  isActivated: boolean;
Weet jij ook hoe je html niet in code zet maar van html component haalt? Want denk dat inhoud van mail stuk uitgebreider wordt dan dit

2024-01-14 18:54 UTC, studentThomas commented on frontend/apps/smart-energy-web/src/app/app.routes.ts
Ik heb nu veranded. Bedoelde je dat? Want met branch wan feat-new-ui staat guard isloggged in bij settings en kan user dus niet bij setting/account om wachtwoord aan te passen

2024-01-14 19:03 UTC, Job79 commented on frontend/libs/core/src/models/user.interface.ts
> +  isActivated: boolean;
Nee geen idee. Maar is niet nodig denk ik? Verwacht niet dat de email zo heel groot zal worden.

2024-01-14 19:20 UTC, Job79 commented on frontend/apps/smart-energy-web/src/app/app.routes.ts
Je wilt alleen naar de settings kunnen gaan wanneer je ingelogt bent, je wilt niet als niet-ingelogde gebruiker naar /settings kunnen navigeren. Maar na deze pull request moet je de account pagina kunnen bezoeken, wat dan inderdaad voor problemen zorgt. 

Maar is het duidelijk voor de gebruiker dat hij zijn wachtwoord moet aanpassen wanneer deze naar de settings word gestuurt? Hij kan nog steeds naar andere setting pagina's navigeren.

Is het mischien niet beter om een apparte pagina te maken waar de gebruiker alleen zijn wachtwoord kan resetten? Hoeft op zich niet in deze pull request, kunnen we ook later nog doen.

2024-01-14 19:24 UTC, Job79 commented on frontend/libs/core/src/models/user.interface.ts
> +  isActivated: boolean;
Heb een migration toegevoegt

2024-01-15 15:13 UTC, Job79 commented
Vervangen door #82

2024-01-15 15:13 UTC, closed without merging